### ISSUE TITLE
Font Awesome Pro (and v6)

### ISSUE THREAD

**Issue by fncll** [cogdog/wp-dimension#10]
Hi Alan, I am wondering if you have suggestions on integrating Font Awesome Pro (v6, not that it necessarily matters) with this theme? The connection between the theme, the font awesome menu plugin, and a child-theme is opaque to me. Options appear to me to be, from what *I* think is best to least optimal:

- Create a child theme (but not sure if that is best for this purpose)
- Copy and hack the theme itself
- Maybe some kind of plugin modification?

Another thought would be to explore making changes to this theme to allow some settings for Font Awesome, such as selecting a version and/or using remote vs packaged fonts, etc.

For the moment I am just brute forcing it by adding a script to the theme's header.php file `<script src="https://kit.fontawesome.com/mysitecode.js" etc></script>` but this is just a *little* inelegant and duplicative!

**Comment by cogdog** [comment]
This will take some investigation. The theme itself is currently using version 5. 

You might be able to child theme it  (which saves you re-edits if/when WP-Dimension is updated) with replacement items for 

assets/css/fontawesome-all.min.css

and all items in:

assets/webfonts

Just guessing here. 

For the front menu icons, I need to update this plugin
https://github.com/cogdog/font-awesome-5-menus/

I'm pretty behind here

**Comment by fncll** [comment]
Child theme was my first thought, but I'm still having trouble to get even a minimal child theme to work, I suspect something with the enqueuing, etc. I'll keep poking around!

**Comment by cogdog** [comment]
You should not have to enqueue any extra things. Let's say your child theme is in a directory named `dimension-child`, and your style.css references `wp-dimension` as template. 

You will need in a functions.php something like this to connect to the parent.

```
add_action('wp_enqueue_scripts', 'add_parent_stuff');

function add_parent_stuff() {
	// hello parents!
    $parent_style = 'wp-dimension';
    wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );

    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
}
```

Then what you want to do is create this directory structure in your child theme:

```
assets/
    css/
    webfonts/
```

Copy your Font AwesomePro version of `fontawesome-all.min.css` into the child theme's `assets/css` and copy all the webfonts into `assets/webfonts` 

Next from wp-dimension `assets/css/main.css` into your child's assets/css directory. The main theme will load this as its style sheet rather the parent, and then use the local files in your child theme assets/webfonts

That might work. The WP-dimension is set to override it's own version of `main.css` for the child theme fileand then it will grab your special font awesome fonts.

Total guesswork

**Comment by fncll** [comment]
I'll dig into it some more and get back to you. I've created child themes before, but for some reason wasn't able to get it working with this theme, this time, even as a completely minimal example that didn't actually do anything. But that was yesterday...when I have a chance in the next few days I will work on it some more!

**Comment by fncll** [comment]
I think I'm going to keep this simple, for the moment, and use the [Advanced Custom Fields: Font Awesome](https://wordpress.org/plugins/advanced-custom-fields-font-awesome/) plugin, child theme or no...if I end up figuring out anything interesting, I'll check back in!
