### ISSUE TITLE
the_content doesn't render correctly

### ISSUE THREAD

**Issue by DrogoNevets** [cogdog/wp-dimension#2]
On the main page, `the_content` function for each page/post doesn't render correctly when used with "Word Press post tabs" plugin.

I lose a good chunk of my content.

Any ideas why this is (works fine on "single page" view)

**Comment by cogdog** [comment]
Got an example I can see and inspect the source code or a screen shot? It's likely a CSS issue, not enough lateral room

**Comment by cogdog** [comment]
Never heard back, so thank for all the fish.
