### ISSUE TITLE
Font Awesome 5 support?

### ISSUE THREAD

**Issue by fncll** [cogdog/wp-dimension#3]
Any chance of an update to support Font Awesome 5? I tried using a custom location in the Font Awesome 4 Menus plugin settings but it didn't quite work (I got a rectangle where there should have been a Mastodon icon which are available in version 5). I also tried adding the v5 info to the header using a plugin, but that didn't seem to work either (probably due to the FA5 change to the css classes used).

At any rate, I might just hack around a bit and try to create a Font Awesome 5 version of the plugin.

**Comment by cogdog** [comment]
Looking into it, the structure of 5 is different, and I use a plugin that does version 4. This script might be a way I toss in to handle version 4 classes to 5. 

https://gist.github.com/timint/fb53929ff196d0a5754188bd93a80cef

**Comment by cogdog** [comment]
And I thought this might help but it does not

https://wordpress.org/support/topic/font-awesome-version-5-update-2/

I think it needs a whole redo approach...

**Comment by fncll** [comment]
Yeah, that's why I was thinking about taking the approach of modifying the plugin...though it might be more straightforward. I would really like to get at a few of the FA5 icons, including Mastodon and some better options for newsletter links.

**Comment by cogdog** [comment]
I'm pretty sure the plugin could be modified, but besides just linking to a CSS it also has to link in a JavaScript file, and the code logic on the parsing of CSS needs some brain work to sort out. Seems worth having better icons I agree.

**Comment by fncll** [comment]
Right...if I do work on the plugin, I will share. But changing the theme in a useful way for others is a different beast because of backward compatibility.

**Comment by cogdog** [comment]
It might be easier to add to the theme, as the plugin does quite a few things not strictly needed. I've got some theme check stuff that I can test for existence of the plugin, and suggest deactivating as an admin notice.

**Comment by cogdog** [comment]
Here is a hacky approach that seems to work. It involves an edit of the plugin:

(1) Comment out lines 164-166 of n9m-font-awesome-4.php

        /*
         if( !in_array( 'fa', $classes ) ){
             array_unshift( $classes, 'fa' );
         }
         */

(2) In the Font Awesome 4 Menus settings, use the option to load CSS from a custom location, I used

https://use.fontawesome.com/releases/v5.6.3/css/all.css

![fa5](https://user-images.githubusercontent.com/463038/50581696-97807a80-0e21-11e9-8a92-d21074c9657b.jpg)

(3) For the menu CSS classes, use the full specs like `fab fa-mastodon`  or 'far fa-clock`

(4) The CSS is  a bit messed up, I had to add custom CSS

```
#menu-social i {
    font-style: normal;
    font-size: 2em;
}
```

It's a bit convoluted, trying to determine best approach for mortals.

**Comment by cogdog** [comment]
Change that, I've done a rewrite to the plugin- give this a spin! https://github.com/cogdog/font-awesome-5-menus

**Comment by fncll** [comment]
It works! I had to remove the label from the menu items, otherwise the label text was showing, which it didn't before, but this behavior is arguably more logical than the original :)

**Comment by fncll** [comment]
Actually, I take that 2nd part back: that was just an artifact in the customizer...turns out you DO need the labels and the text doesn't show up in the "real" thing! Thanks for fixing this (I've been too busy torturing myself with learning some Python to even make a crack at it).

**Comment by cogdog** [comment]
The labels are supposed to wrap below, but never seem right. I prefer label-less.... in my themes I hide them just in case with CSS

```
span.fontawesome-text {
    display: none;
}
```
