### ISSUE TITLE
Mailto link in social media menu?

### ISSUE THREAD

**Issue by fncll** [cogdog/wp-dimension#6]
Is there a way to have an email item in the Social Media menu (I'm using the `fas fa-envelope` CSS class to show an envelope) link properly to a mailto: address?

I thought this used to work (or maybe I didn't test properly), but now the link gets converted to something like https://gmail.com/ or similar. I see this on some of the example sites you link to as well. 

If I edit the link to mailto:xxx then the text label appears, if I remove the label, the resulting icon is small and non-functional.

**Comment by fncll** [comment]
Never mind. This is just quirky display in the customizer when fixing. I am seeing a similar problem in other sites with what was an email link converting to a web link as described above though (for example, see the email icon at http://tomfullerton.ca/ ), which maybe happened as part of WP upgrades or something!

**Comment by cogdog** [comment]
I was able to reproduce what you describe (I almost never do menus in the customizer) - has the text "email" next to the envelope in the preview, but if published, it looks ok. 

It's likely the way that the customizer generates the preview; there might be some extra javascript needed to generate previews correctly for a `mailto:` link.

In Tom's case, from insepcting the link, it looks like he inadvertently as it entered as `href="http://mailto:*******@*****.***)` the `http://` in front is the problem.

**Comment by fncll** [comment]
The weird thing is, that's what mine was too, when I edited this morning, `http://mailto...` but I am 99% certain that wasn't the case last time I edited the site (which was a long, long time ago). I rarely use the customizer, either, but I was editing some additional CSS and it was expedient 😄 -- Ah well, no real issue left at this point.
