### ISSUE TITLE
Change front box background

### ISSUE THREAD

**Issue by nige365** [cogdog/wp-dimension#7]
Hi, this is my first post so sorry if I have missed something obvious, we are using this templates for my wife’s personal training work, I have used an Wordpress plugin to pull in the google reviews, however I need to create a white background so that it is readable, I have tried the options on the page but guess I need some custom css, anyone have any ideas how I could do this please? Please see http://www.ptbecca.co.uk/#reviews to understand my problem. Thanks you

**Comment by nige365** [comment]
It’s ok I have done it, it was simple change an option on the review widget

**Comment by cogdog** [comment]
Glad you figured it out- The PT Becca site is looking very strong! I was going to add it as an example but I already had it there. Thanks for making great use of this theme.

**Comment by nige365** [comment]
Hey, it’s a great theme thanks for making it, have thoroughly enjoyed creating the site for my partner and will continue to adapt as we go, will be sure to make a donation once we are back on our feet, thanks 🙏
